[package]
name = "basws-shared"
version = "0.1.0"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chrono = "0.4"
serde = "1"
serde_derive = "1"
uuid = { version = "0.8", features = ["v4", "serde"] }
